options (skip=1)
LOAD DATA
INFILE 'item_assign_to_org.csv'
INTO TABLE item_org_mapping
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
ITEM_CODE 				"TRIM(:ITEM_CODE)" ,
TARGET_ORG				"TRIM(:TARGET_ORG)" ,
TARGET_ORG_ID			"TRIM(:TARGET_ORG_ID)"
)