PACKAGE XXFIL_BOM_UPLOAD IS
  gn_user_id          NUMBER := FND_PROFILE.VALUE('USER_ID');
  gn_resp_id          NUMBER := FND_PROFILE.VALUE('RESP_ID');
  gn_resp_appl_id     NUMBER := FND_PROFILE.VALUE('RESP_APPL_ID');
  gn_request_id       NUMBER := FND_PROFILE.VALUE('CONC_REQUEST_ID');
  gn_org_id           NUMBER := FND_PROFILE.VALUE('ORG_ID');
 PROCEDURE UPLOAD_DATA ; 
 PROCEDURE MAIL_TO_APPROVER ; 
 PROCEDURE APPROVE_BUTTON ;
 PROCEDURE REJECT_BUTTON ;
 PROCEDURE DYNAMIC_APPROVAL ; 
END;