BEGIN
XXQGEN_REQ_DATA_LOAD_PKG_AR.MAIN ;
END ;



/

SELECT * FROM XXQGEN_PO_REQ_HEADERS_STG_AR


TRUNCATE TABLE XXQGEN_PO_REQ_HEADERS_STG_AR
/

SELECT * FROM XXQGEN_PO_REQ_LINES_STG_AR

TRUNCATE TABLE XXQGEN_PO_REQ_LINES_STG_AR


/


select * from fnd_user where user_name  = 'DSINGH'


select * from po_requisitions_interface_all where created_by = 1016248 

select * from po_interface_errors where created_by = 1016248 


SELECT * FROM PO_REQUISITION_HEADERS_ALL WHERE  created_by = 1016248 --AND  ATTRIBUTE9 =7598713

SELECT * FROM PO_REQUISITION_LINES_ALL WHERE  created_by = 1016248 --AND  REQUISITION_HEADER_ID IN (593935 , 593937,593936)

SELECT * FROM PO_REQ_DISTRIBUTIONS_ALL  WHERE  created_by = 1016243 AND REQUISITION_LINE_ID BETWEEN 643730 AND 643737


SELECT * FROM GL_CODE_COMBINATIONS
WHERE SEGMENT1||' '||SEGMENT2||' '||SEGMENT3||' '||SEGMENT4||' '||SEGMENT5 =   '01 510 7530 0000 000'
/

SELECT * FROM XXQGEN_REQ_hdr_STG_TBL_AK
/
SELECT * FROM XXQGEN_REQ_LINE_STG_TBL_AK
/
SELECT * FROM XXQGEN_REQ_DIST_STG_TBL_AK