SELECT PRHA.SEGMENT1
,PRHA.REQUISITION_HEADER_ID
, HDR.PREPARER
, HDR.OPERATING_UNIT
, HDR.AUTHORIZATION_STATUS
, HDR.DESCRIPTION
, HDR.REQUISITION_TYPE
, HDR.PROCESS_FLAG
, PRLA.REQUISITION_LINE_ID
, LINE.LINE_TYPE
, LINE.ITEM_NUMBER
, LINE.ITEM_DESCRIPTION
, LINE.CATEGORY
, LINE.UOM
, LINE.QUANTITY
, LINE.UNIT_PRICE
, LINE.CURRENCY_CODE
, LINE.REQUESTER
, LINE.NEED_BY_DATE
, LINE.ORGANIZATION
, LINE.SUPPLIER
, LINE.SITE
, LINE.CONTACT
, LINE.PHONE
, LINE.DESTINATION_TYPE
, LINE.SOURCE
, PRDA.DISTRIBUTION_ID
, LINE.CHARGE_ACCOUNT
FROM XXQGEN_PO_REQ_HEADERS_STG_AR HDR 
, XXQGEN_PO_REQ_LINES_STG_AR LINE
, PO_REQUISITION_HEADERS_ALL PRHA
, PO_REQUISITION_LINES_ALL PRLA
, PO_REQ_DISTRIBUTIONS_ALL PRDA
WHERE 1=1
AND HDR.REQUISITION_NUMBER = LINE.REQUISITION_NUMBER
AND HDR.PROCESS_FLAG = 'V'
AND LINE.PROCESS_FLAG = 'V'
AND HDR.REQUEST_ID= PRHA.ATTRIBUTE7
AND PRHA.REQUISITION_HEADER_ID = PRLA.REQUISITION_HEADER_ID
AND PRLA.REQUISITION_LINE_ID = PRDA.REQUISITION_LINE_ID



SELECT PRHA.SEGMENT1
,PRHA.REQUISITION_HEADER_ID
,HDR.PREPARER
, HDR.OPERATING_UNIT
, HDR.AUTHORIZATION_STATUS
, HDR.DESCRIPTION
, HDR.REQUISITION_TYPE
, HDR.PROCESS_FLAG
, HDR.ERROR_MESSAGE
,PRLA.REQUISITION_LINE_ID
, LINE.LINE_TYPE
, LINE.ITEM_NUMBER
, LINE.ITEM_DESCRIPTION
, LINE.CATEGORY
, LINE.UOM
, LINE.QUANTITY
, LINE.UNIT_PRICE
, LINE.CURRENCY_CODE
, LINE.REQUESTER
, LINE.NEED_BY_DATE
, LINE.ORGANIZATION
, LINE.SUPPLIER
, LINE.SITE
, LINE.CONTACT
, LINE.PHONE
, LINE.DESTINATION_TYPE
, LINE.SOURCE
,PRDA.DISTRIBUTION_ID
,PRDA.CODE_COMBINATION_ID
, LINE.CHARGE_ACCOUNT
, LINE.ERROR_MESSAGE
FROM XXQGEN_PO_REQ_HEADERS_STG_AR HDR 
, XXQGEN_PO_REQ_LINES_STG_AR LINE
, PO_REQUISITION_HEADERS_ALL PRHA
, PO_REQUISITION_LINES_ALL PRLA
, PO_REQ_DISTRIBUTIONS_ALL PRDA
WHERE 1=1
AND HDR.REQUISITION_NUMBER = LINE.REQUISITION_NUMBER
AND HDR.PROCESS_FLAG = 'E'
AND LINE.PROCESS_FLAG = 'E'
AND HDR.REQUEST_ID= PRHA.ATTRIBUTE7
AND PRHA.REQUISITION_HEADER_ID = PRLA.REQUISITION_HEADER_ID
AND PRLA.REQUISITION_LINE_ID = PRDA.REQUISITION_LINE_ID






FOR REC IN (

SELECT PRHA.SEGMENT1 
, PRHA.REQUISITION_HEADER_ID
 , PRHA.ATTRIBUTE7 
 , PRHA.ATTRIBUTE8 
 , PRLA.REQUISITION_LINE_ID
  ,PRLA.ATTRIBUTE7 LINE7
  , PRLA.ATTRIBUTE8  LINE8
  ,  PRDA.DISTRIBUTION_ID
FROM PO_REQUISITION_HEADERS_ALL PRHA
, PO_REQUISITION_LINES_ALL PRLA
, PO_REQ_DISTRIBUTIONS_ALL PRDA
WHERE 1=1
AND PRHA.REQUISITION_HEADER_ID = PRLA.REQUISITION_HEADER_ID
AND PRLA.REQUISITION_LINE_ID = PRDA.REQUISITION_LINE_ID
AND PRHA.ATTRIBUTE7 = gn_request_id )

LOOP

UPDATE XXQGEN_PO_REQ_HEADERS_STG_AR
SET PROCESS_FLAG = 'P'
, REQUISITION_NUMBER = REC.SEGMENT1
, REQUISITION_HEADER_ID  = REC.REQUISITION_HEADER_ID
WHERE RECORD_ID = REC.ATTRIBUTE8
REQUEST_ID = REC.ATTRIBUTE7

UPDATE XXQGEN_PO_REQ_LINES_STG_AR
SET PROCESS_FLAG = 'P'
, REQUISITION_LINE_ID  = REC.REQUISITION_LINE_ID
, DISTRIBUTION_ID = REC.DISTRIBUTION_ID
WHERE REQUEST_ID = REC.LINE7
AND RECORD_ID = REC.LINE8

END LOOP ;
END 